
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword       # Contraseña para el usuario root
      MYSQL_DATABASE: weather_db               # Base de datos que se creará automáticamente
      MYSQL_USER: usuario123                   # Usuario que usaremos para la conexión
      MYSQL_PASSWORD: clave123                 # Contraseña para el usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql             # Persistencia de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:0.234.0
    container_name: n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_HOST=localhost

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

  deepseek:
    build:
      context: ./deepseek
      dockerfile: Dockerfile
    container_name: deepseek
    ports:
      - "11435:11434"             # Mapeamos el puerto 11435 en el host
    environment:
      - MODEL=deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
    volumes:
      - deepseek_data:/data
    restart: always

  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    container_name: python-api
    ports:
      - "6000:5000"               # Mapeamos el puerto interno 5000 al 6000 en el host
    restart: always

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: admin-panel
    ports:
      - "8085:8080"               # Mapeamos el puerto interno 8080 al 8085 en el host
    volumes:
      - admin_data:/app/data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword         # Debe coincidir con MYSQL_ROOT_PASSWORD
    ports:
      - "8081:80"                        # Acceso a phpMyAdmin desde el host en el puerto 8081
    depends_on:
      - mysql

volumes:
  n8n_data:
  deepseek_data:
  admin_data:
  mysql_data:
